import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
const profile = JSON.parse(fs.readFileSync(path.join(root, 'content/profile.json'), 'utf8'));
const projects = JSON.parse(fs.readFileSync(path.join(root, 'content/projects.json'), 'utf8'));
const e = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fs.mkdirSync(out, { recursive: true });
fs.cpSync(path.join(root, 'public'), out, { recursive: true });
function write(name, text) { const p = path.join(out, name); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, text); }
const arrow = '<span aria-hidden="true">↗</span>';
const tags = items => `<ul class="tags" aria-label="Technologies">${items.map(t=>`<li>${e(t)}</li>`).join('')}</ul>`;
function frame(title, description, route, body, isHome=false) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${e(title)}</title><meta name="description" content="${e(description)}"><meta name="author" content="${e(profile.name)}">
<meta name="theme-color" content="#111e2d"><link rel="canonical" href="${profile.url}${route}">
<meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${profile.url}${route}"><meta property="og:site_name" content="${e(profile.name)}">
<meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css">
</head><body><a class="skip" href="#main">Skip to content</a>
<header class="header"><div class="wrap nav"><a class="wordmark" href="/" aria-label="${e(profile.name)} home">JS<span class="brand-dot">.</span></a><nav aria-label="Main navigation"><a href="/#work">Work</a><a href="/#experience">Experience</a><a href="/#about">About</a><a class="nav-resume" href="/resume/">Résumé ${arrow}</a></nav></div></header>
<main id="main">${body}</main>
<footer><div class="wrap footer"><span>© ${new Date().getUTCFullYear()} ${e(profile.name)}</span><div><a href="${profile.github}">GitHub ${arrow}</a><a href="${profile.linkedin}">LinkedIn ${arrow}</a><a href="mailto:${profile.email}">Email ${arrow}</a></div><a href="#main">Back to top ↑</a></div></footer>
</body></html>`;
}
function figure(p, compact=false) {
 return `<div class="pipeline ${e(p.accent)} ${compact?'compact':''}" role="group" aria-label="${e(p.figureLabel)}"><div class="diagram-label"><span>${e(p.figureLabel)}</span><span aria-hidden="true">${p.slug==='shabad-shazam'?'ƒ(audio)':p.slug==='neuro-data-lab'?'EEG → class':p.slug==='drivesafe'?'frame → state':'UI → data'}</span></div><ol>${p.flow.map((v,i)=>`<li><span class="step">0${i+1}</span><span>${e(v)}</span>${i<3?'<span class="flow-arrow" aria-hidden="true">→</span>':''}</li>`).join('')}</ol></div>`;
}
const projectCards = projects.map((p,i)=>`<article class="project-card"><a class="project-visual" href="/projects/${p.slug}/" aria-label="Read ${e(p.name)} case study">${figure(p,true)}</a><div class="project-copy"><div class="eyebrow"><span>0${i+1} / ${e(p.category)}</span></div><h3><a href="/projects/${p.slug}/">${e(p.name)} ${arrow}</a></h3><p>${e(p.summary)}</p>${tags(p.tech)}<a class="text-link" href="/projects/${p.slug}/">Read case study <span aria-hidden="true">→</span></a></div></article>`).join('');
const sectionTop = (num, label, title, description='') => `<div class="section-head"><p class="eyebrow">${num} / ${label}</p><h2>${title}</h2>${description?`<p>${description}</p>`:''}</div>`;
const home = `
<section class="hero"><div class="wrap"><div class="hero-kicker"><span class="status-dot" aria-hidden="true"></span> Software developer · Pune, India</div><div class="hero-grid"><div><h1>Jagjeevan<br>Singh Soni<span class="lime-text">.</span></h1><p class="hero-intro">${e(profile.intro)}</p><div class="hero-actions"><a class="button primary" href="#work">Explore my work <span aria-hidden="true">↓</span></a><a class="button outline" href="/resume/">View résumé ${arrow}</a></div></div><aside class="hero-note"><span class="eyebrow">Currently</span><h2>Building at<br>Amdocs.</h2><p>Enterprise telecom.<br>Backend engineering.<br>Thoughtful automation.</p><div class="note-rule"></div><span class="eyebrow">Beyond the day job</span><p>Audio recognition, computer vision, and the systems behind them.</p><a href="${profile.github}">On GitHub ${arrow}</a></aside></div><div class="hero-bottom"><span>Engineering, from idea to delivery.</span><span>Java / Python / Systems</span></div></div></section>
<section class="section wrap" id="work">${sectionTop('01','Selected work','Four projects. Different ways<br>to connect software to the world.')}<div class="project-grid">${projectCards}</div></section>
<section class="experience-section" id="experience"><div class="wrap section experience-layout"><div>${sectionTop('02','Experience','Software that supports<br>real operations.')}<div class="company"><span class="company-monogram" aria-hidden="true">A</span><div><h3>Amdocs</h3><p>${e(profile.experience.period)}<br>Pune, India</p></div></div><p class="role-line"><strong>${e(profile.experience.current)}</strong><br><span>Previously ${e(profile.experience.previous)}</span></p></div><div class="experience-list">${profile.experience.areas.map((a,i)=>`<article><span class="list-number">0${i+1}</span><div><h3>${e(a.title)}</h3><p>${e(a.text)}</p></div></article>`).join('')}</div></div></section>
<section class="section wrap" id="about"><div class="about-grid"><div>${sectionTop('03','About','Practical experience.<br>A curious engineering mind.')}<p class="lead">${e(profile.about)}</p><p>${e(profile.direction)}</p><p class="languages">English · Punjabi · Hindi</p></div><aside class="education"><span class="eyebrow">Education / 2019–2023</span><h3>${e(profile.education.degree)}</h3><p>${e(profile.education.school)}<br>${e(profile.education.location)}</p><div class="grade">7.71<span>/ 10 CGPA</span></div><p class="focus">${e(profile.education.focus)}</p><details><summary>Relevant coursework <span aria-hidden="true">+</span></summary><ul>${profile.education.courses.map(c=>`<li>${e(c)}</li>`).join('')}</ul></details></aside></div><div class="skills-grid">${profile.skills.map(s=>`<div><h3>${e(s.group)}</h3><p>${s.items.map(e).join(' · ')}</p></div>`).join('')}</div></section>
<section class="recognition-section"><div class="wrap section">${sectionTop('04','Recognition & learning','Growth, in practice.')}<div class="recognition-grid">${profile.recognition.map(r=>`<article><span class="small-label">${e(r.org)}</span><h3>${e(r.title)}</h3><p>${e(r.text)}</p></article>`).join('')}</div></div></section>
<section class="wrap section community">${sectionTop('05','Beyond engineering','Teams, campus & community.')}<div class="community-grid">${profile.community.map(c=>`<article><h3>${e(c.title)}</h3><span class="small-label">${e(c.org)}</span><p>${e(c.text)}</p></article>`).join('')}</div></section>
<section class="contact"><div class="wrap contact-inner"><div><p class="eyebrow">Get in touch</p><h2>Let’s start a<br>conversation<span class="lime-text">.</span></h2></div><div><p>For software engineering, graduate study,<br>or a conversation about a project.</p><a class="email-link" href="mailto:${profile.email}">${profile.email} ${arrow}</a><div class="contact-links"><a href="${profile.linkedin}">LinkedIn ${arrow}</a><a href="${profile.github}">GitHub ${arrow}</a></div></div></div></section>`;
write('index.html', frame(`${profile.name} — Software Developer`, 'Software developer at Amdocs. Explore enterprise software experience and projects in audio recognition, EEG classification, computer vision, and web applications.', '/', home, true));
projects.forEach((p,i)=>{
 const next=projects[(i+1)%projects.length];
 const body=`<section class="case-hero"><div class="wrap"><a class="back-link" href="/#work">← All projects</a><p class="eyebrow">0${i+1} / ${e(p.category)}</p><h1>${e(p.name)}</h1><p class="case-summary">${e(p.summary)}</p><div class="case-meta"><span>${e(p.type)}</span><span>${e(p.status)}</span></div>${tags(p.tech)}</div></section><div class="wrap case-diagram">${figure(p)}</div><section class="wrap case-body"><aside class="case-sidebar"><h2>On this page</h2><a href="#overview">Overview</a><a href="#contribution">Contribution</a><a href="#approach">Approach</a><a href="#results">Results & scope</a><a href="#reflection">Reflection</a></aside><div class="case-text"><section id="overview"><p class="eyebrow">The question</p><h2>${e(p.question)}</h2><p>${e(p.context)}</p></section><section id="contribution"><h2>My contribution</h2><p>${e(p.role)}</p></section><section id="approach"><h2>How it works</h2>${p.work.map((w,j)=>`<article class="approach"><span class="list-number">0${j+1}</span><div><h3>${e(w.title)}</h3><p>${e(w.text)}</p></div></article>`).join('')}</section><section id="results"><h2>Results & scope</h2>${p.metric?`<div class="result"><strong>${e(p.metric.value)}</strong><span>${e(p.metric.label)}</span></div>`:''}<p>${e(p.outcome)}</p><div class="scope-note"><h3>Evaluation boundary</h3><p>${e(p.limits)}</p></div></section><section id="reflection"><h2>Engineering reflection</h2><p>${e(p.takeaway)}</p></section></div></section><div class="wrap next-project"><span class="eyebrow">Next case study</span><a href="/projects/${next.slug}/">${e(next.name)} ${arrow}</a></div>`;
 write(`projects/${p.slug}/index.html`,frame(`${p.name} — ${profile.name}`,p.summary,`/projects/${p.slug}/`,body));
});
const resume=`<section class="wrap section resume-page"><a class="back-link" href="/">← Back to portfolio</a><div class="resume-heading"><div><p class="eyebrow">Professional résumé</p><h1>${e(profile.name)}</h1><p>${e(profile.role)} · ${e(profile.location)}</p></div><a class="button dark" href="/assets/Jagjeevan_Singh_Soni_Resume.pdf" download>Download PDF ↓</a></div><p class="resume-summary">${e(profile.about)}</p><div class="resume-section"><h2>Experience</h2><h3>Amdocs · ${e(profile.experience.current)}</h3><p class="small-label">${e(profile.experience.period)} · Previously ${e(profile.experience.previous)}</p><ul>${profile.experience.areas.map(a=>`<li>${e(a.text)}</li>`).join('')}</ul></div><div class="resume-section"><h2>Education</h2><h3>${e(profile.education.degree)}</h3><p>${e(profile.education.school)} · ${e(profile.education.period)}<br>${e(profile.education.grade)} · ${e(profile.education.focus)}</p></div><div class="resume-section"><h2>Selected projects</h2>${projects.map(p=>`<article><h3><a href="/projects/${p.slug}/">${e(p.name)} ${arrow}</a></h3><p>${e(p.summary)}</p><p class="small-label">${p.tech.map(e).join(' · ')}<br>${e(p.status)}</p></article>`).join('')}</div><div class="resume-section"><h2>Technical skills</h2>${profile.skills.map(s=>`<p><strong>${e(s.group)}:</strong> ${s.items.map(e).join(', ')}</p>`).join('')}</div><div class="resume-section"><h2>Recognition & leadership</h2>${[...profile.recognition.slice(0,2),...profile.community].map(x=>`<p><strong>${e(x.title)}</strong> · ${e(x.org)}<br>${e(x.text)}</p>`).join('')}</div><p><a href="mailto:${profile.email}">${profile.email}</a> · <a href="${profile.linkedin}">LinkedIn</a> · <a href="${profile.github}">GitHub</a></p></section>`;
write('resume/index.html',frame(`Résumé — ${profile.name}`,'Experience, education, projects, and technical skills. Download the professional résumé as a PDF.','/resume/',resume));
write('404.html',frame(`Page not found — ${profile.name}`,'Return to the portfolio homepage.','/404.html',`<section class="wrap section not-found"><p class="eyebrow">404 / Page not found</p><h1>This page has<br>moved off course.</h1><p>You can find my experience and selected projects on the homepage.</p><a class="button dark" href="/">Back to the portfolio →</a></section>`));
write('.nojekyll','');
write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${profile.url}/sitemap.xml\n`);
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/resume/',...projects.map(p=>`/projects/${p.slug}/`)].map(u=>`<url><loc>${profile.url}${u}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${projects.length+3} HTML pages in dist/`);
