import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
const profile = JSON.parse(fs.readFileSync(path.join(root, 'content/profile.json'), 'utf8'));
const projects = JSON.parse(fs.readFileSync(path.join(root, 'content/projects.json'), 'utf8'));
const e = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fs.mkdirSync(out, { recursive: true });
fs.cpSync(path.join(root, 'public'), out, { recursive: true });
function write(name, text) { const p = path.join(out, name); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, text); }
const arrow = '<span aria-hidden="true">↗</span>';
const tags = items => `<ul class="tags" aria-label="Technologies">${items.map(t=>`<li>${e(t)}</li>`).join('')}</ul>`;

const icon = name => {
 const shapes = {email:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="m3 7 9 6 9-6"/>',linkedin:'<rect x="3" y="3" width="18" height="18" rx="4"/><path d="M7 10v7m0-10v.1M11 17v-7m0 3c0-4 6-4 6 0v4"/>',github:'<path d="M9 19c-5 1-5-3-7-3m14 5v-4c0-1-.3-2-1-2 4-.5 6-2 6-6 0-1-.5-3-1-3 0-1 0-3-.5-3-2 0-3 1-3 1-3-1-5-1-8 0 0 0-1-1-3-1-.5 0-.5 2-.5 3-1 1-1 2-1 3 0 4 2 5.5 6 6-.7.5-1 1-1 2v4"/>',resume:'<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9zM14 3v6h6M8 13h8M8 17h5"/>',theme:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>'};
 return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+shapes[name]+'</svg>';
};
const portrait = () => profile.photo ? '<img class="portrait" src="'+e(profile.photo)+'" alt="'+e(profile.name)+'" width="200" height="200">' : '<div class="portrait portrait-placeholder" role="img" aria-label="Profile photo placeholder"><svg viewBox="0 0 200 200" fill="none" aria-hidden="true"><circle cx="100" cy="76" r="30"/><path d="M40 173c0-58 120-58 120 0"/></svg></div>';
const brandLogo = (brand, label, symbolOnly=false) => '<span class="brand-frame brand-'+brand+'">'+(symbolOnly?'<span class="brand-symbol-window">':'')+'<img src="/assets/'+brand+(brand==='amdocs'?'-symbol.':'-logo.')+(brand==='amdocs'?'svg':'png')+'" alt="'+label+' logo" width="56" height="56">'+(symbolOnly?'</span>':'')+'</span>';
const actions = () => '<div class="profile-actions">'+[['email','Email','mailto:'+profile.email],['linkedin','LinkedIn',profile.linkedin],['github','GitHub',profile.github],['resume','View Resume','/assets/Jagjeevan_Singh_Soni_Resume.pdf']].map(([key,label,url])=>'<a class="action action-'+key+'" href="'+e(url)+'" aria-label="'+label+'" '+(key!=='email'?'target="_blank" rel="noopener noreferrer"':'')+'>'+icon(key)+'<span>'+label+'</span></a>').join('')+'<button class="action theme-toggle" type="button" aria-label="Switch to light theme" aria-pressed="false">'+icon('theme')+'<span>Theme</span></button></div>';

function frame(title, description, route, body, isHome=false) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${e(title)}</title><meta name="description" content="${e(description)}"><meta name="author" content="${e(profile.name)}">
<meta name="theme-color" content="#111e2d"><link rel="canonical" href="${profile.url}${route}">
<meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${profile.url}${route}"><meta property="og:site_name" content="${e(profile.name)}">
<meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css">
<script src="/theme.js"></script></head><body class="${isHome?'home-page':'inner-page'}"><a class="skip" href="#main">Skip to content</a>
${isHome?`<header class="scroll-header" inert><div class="scroll-nav"><a class="mini-profile" href="#overview" aria-label="Back to overview">${portrait()}</a>${actions()}</div></header>`:`<header class="header"><div class="wrap nav"><a class="home-link" href="/">${e(profile.name)}</a><nav aria-label="Main navigation"><a href="/#work">Projects</a><a href="/#experience">Experience</a><a href="/resume/">View Resume ${arrow}</a></nav></div></header>`}
<main id="main">${body}</main>
<footer><div class="wrap footer"><span>© ${new Date().getUTCFullYear()} ${e(profile.name)}</span><div><a href="${profile.github}">GitHub ${arrow}</a><a href="${profile.linkedin}">LinkedIn ${arrow}</a><a href="mailto:${profile.email}">Email ${arrow}</a></div><a href="#main">Back to top ↑</a></div></footer>
${isHome?'<script src="/overview.js" defer></script>':''}</body></html>`;
}
function figure(p, compact=false) {
 return `<div class="pipeline ${e(p.accent)} ${compact?'compact':''}" role="group" aria-label="${e(p.figureLabel)}"><div class="diagram-label"><span>${e(p.figureLabel)}</span><span aria-hidden="true">${p.slug==='shabad-shazam'?'ƒ(audio)':p.slug==='neuro-data-lab'?'EEG → class':p.slug==='drivesafe'?'frame → state':'UI → data'}</span></div><ol>${p.flow.map((v,i)=>`<li><span>${e(v)}</span>${i<3?'<span class="flow-arrow" aria-hidden="true">→</span>':''}</li>`).join('')}</ol></div>`;
}
const projectCards = projects.map((p,i)=>`<article class="project-card"><a class="project-visual" href="/projects/${p.slug}/" aria-label="Read ${e(p.name)} case study">${figure(p,true)}</a><div class="project-copy"><div class="eyebrow"><span>${e(p.category)}</span></div><h3><a href="/projects/${p.slug}/">${e(p.name)} ${arrow}</a></h3><p>${e(p.summary)}</p>${tags(p.tech)}<a class="text-link" href="/projects/${p.slug}/">Read case study <span aria-hidden="true">→</span></a></div></article>`).join('');
const sectionTop = (num, label, title, description='') => `<div class="section-head"><p class="eyebrow">${label}</p><h2>${title}</h2>${description?`<p>${description}</p>`:''}</div>`;
const panelViews = `
<section class="panel-view" data-panel="experience" aria-labelledby="panel-title-experience"><div class="panel-view-heading"><span class="eyebrow">Experience</span><h2 id="panel-title-experience">Software that supports real operations</h2><p>Enterprise telecom systems, delivery ownership, and automation at Amdocs.</p></div><div class="panel-company">${brandLogo('amdocs','Amdocs')}<div><h3>Amdocs</h3><p>${e(profile.experience.current)} · ${e(profile.experience.period)}</p></div></div><div class="panel-list">${profile.experience.areas.map(a=>`<article><span class="panel-symbol" aria-hidden="true">↗</span><div><h3>${e(a.title)}</h3><p>${e(a.text)}</p></div></article>`).join('')}</div></section>
<section class="panel-view" data-panel="education" aria-labelledby="panel-title-education"><div class="panel-view-heading"><span class="eyebrow">Education</span><h2 id="panel-title-education">Foundations in computing and mathematics.</h2><p>A Bachelor of Engineering shaped the way I approach systems, data, and software.</p></div><article class="detail-card school-detail">${brandLogo('thapar','Thapar Institute')}<div><span class="eyebrow">July 2019 — June 2023</span><h3>${e(profile.education.degree)}</h3><p>${e(profile.education.school)} · ${e(profile.education.location)}</p><strong>${e(profile.education.grade)}</strong><p>${e(profile.education.focus)}</p></div></article><div class="course-cloud">${profile.education.courses.map(c=>`<span>${e(c)}</span>`).join('')}</div></section>
<section class="panel-view" data-panel="projects" aria-labelledby="panel-title-projects"><div class="panel-view-heading"><span class="eyebrow">Projects</span><h2 id="panel-title-projects">Ideas turned into working systems.</h2><p>Selected work across audio recognition, EEG classification, computer vision, and full-stack applications.</p></div><div class="panel-projects">${projectCards}</div></section>
<section class="panel-view" data-panel="skills" aria-labelledby="panel-title-skills"><div class="panel-view-heading"><span class="eyebrow">Skills</span><h2 id="panel-title-skills">Tools for building useful software.</h2><p>From backend services and databases to scientific computing and delivery automation.</p></div><div class="panel-skills">${profile.skills.map(s=>`<article class="detail-card"><span class="panel-symbol" aria-hidden="true">⌘</span><h3>${e(s.group)}</h3><p>${s.items.map(e).join(' · ')}</p></article>`).join('')}</div></section>
<section class="panel-view" data-panel="recognition" aria-labelledby="panel-title-recognition"><div class="panel-view-heading"><span class="eyebrow">Recognition</span><h2 id="panel-title-recognition">Work that earns trust.</h2><p>Recognition for ownership, reliability, and turning technical work into dependable outcomes.</p></div><div class="panel-recognition"><article class="detail-card"><span class="panel-symbol" aria-hidden="true">✦</span><span class="small-label">${e(profile.recognition[0].org)}</span><h3>${e(profile.recognition[0].title)}</h3><p>${e(profile.recognition[0].text)}</p></article><article class="detail-card"><span class="panel-symbol" aria-hidden="true">↗</span><span class="small-label">Selected project</span><h3>${e(projects[0].name)}</h3><p>${e(projects[0].summary)}</p></article></div></section>
<section class="panel-view" data-panel="certifications" aria-labelledby="panel-title-certifications"><div class="panel-view-heading"><span class="eyebrow">Certifications</span><h2 id="panel-title-certifications">Learning, continued.</h2><p>Practical programs and security training that extend my engineering practice.</p></div><div class="panel-recognition">${profile.recognition.slice(2).map(r=>`<article class="detail-card"><span class="panel-symbol" aria-hidden="true">◇</span><span class="small-label">${e(r.org)}</span><h3>${e(r.title)}</h3><p>${e(r.text)}</p></article>`).join('')}</div></section>`;
const home = `
<section class="landing" id="overview" aria-label="Profile overview"><div class="landing-grid">
<div class="profile-block"><div class="portrait-frame">${portrait()}</div><p class="eyebrow profile-greeting">Hello, I’m</p><h1>Jagjeevan<br>Singh Soni</h1><div class="role-identity">${brandLogo('amdocs','Amdocs')}<p class="current-role">${e(profile.experience.current)} <span>at</span> <strong>${e(profile.experience.company)}</strong></p></div><p class="profile-location">${icon('pin')}${e(profile.location)}</p>${actions()}</div>
<div class="overview-panel" id="overview-panel" tabindex="0" role="region" aria-label="Portfolio sections">
<section class="panel-view is-active" data-panel="overview" aria-labelledby="panel-title-overview">
<div class="panel-intro"><span class="eyebrow">Overview</span><h2 id="panel-title-overview" class="intro-statement">${e(profile.intro)}</h2><p>${e(profile.overviewSummary)}</p></div>
<article class="overview-card journey-card" aria-label="Education and career timeline"><ol class="journey-timeline" aria-label="Most recent first"><li class="journey-step journey-current"><span class="journey-marker" aria-hidden="true"></span>${brandLogo('amdocs','Amdocs')}<div class="journey-copy"><div class="journey-heading"><h3>${e(profile.experience.company)}</h3><span class="journey-date">2023 – Present</span></div><p>${e(profile.experience.current)}</p></div></li><li class="journey-step"><span class="journey-marker" aria-hidden="true"></span>${brandLogo('thapar','Thapar Institute',true)}<div class="journey-copy"><div class="journey-heading"><h3>${e(profile.education.school)}</h3><span class="journey-date">2019 – 2023</span></div><p>Bachelor of Engineering</p></div></li></ol></article>
<article class="overview-card technologies-card"><div class="card-label"><span class="card-symbol" aria-hidden="true">⌘</span><h3>Technologies &amp; Skills</h3></div><ul class="skill-pills">${profile.overviewSkills.map(x=>'<li>'+e(x)+'</li>').join('')}</ul></article>
<article class="overview-card testimonial-placeholder"><div class="card-label"><span class="card-symbol quote-symbol" aria-hidden="true">“</span><h3>Testimonials</h3><span class="small-label">Coming soon</span></div><p>A space for words from people I’ve worked with.</p></article>
</section>${panelViews}</div></div></section>
<nav class="bottom-ribbon" aria-label="Portfolio sections">${[['overview','Overview'],['experience','Experience'],['education','Education'],['projects','Projects'],['skills','Skills'],['recognition','Recognition'],['certifications','Certifications']].map(([id,label],i)=>'<a href="#overview-panel" data-panel-target="'+id+'"'+(i===0?' aria-current="location"':'')+'>'+label+'</a>').join('')}</nav>
<section class="section wrap" id="work">${sectionTop('01','Selected work','Four projects. Different ways<br>to connect software to the world.')}<div class="project-grid">${projectCards}</div></section>
<section class="experience-section" id="experience"><div class="wrap section experience-layout"><div>${sectionTop('02','Experience','Software that supports<br>real operations.')}<div class="company">${brandLogo('amdocs','Amdocs')}<div><h3>Amdocs</h3><p>${e(profile.experience.period)}<br>Pune, India</p></div></div><p class="role-line"><strong>${e(profile.experience.current)}</strong><br><span>Previously ${e(profile.experience.previous)}</span></p></div><div class="experience-list">${profile.experience.areas.map((a,i)=>`<article><div><h3>${e(a.title)}</h3><p>${e(a.text)}</p></div></article>`).join('')}</div></div></section>
<section class="section wrap" id="about"><div class="about-grid"><div>${sectionTop('03','About','Practical experience.<br>A curious engineering mind.')}<p class="lead">${e(profile.about)}</p><p>${e(profile.direction)}</p><p class="languages">English · Punjabi · Hindi</p></div><aside class="education">${brandLogo('thapar','Thapar Institute')}<span class="eyebrow">Education / 2019–2023</span><h3>${e(profile.education.degree)}</h3><p>${e(profile.education.school)}<br>${e(profile.education.location)}</p><div class="grade">7.71<span>/ 10 CGPA</span></div><p class="focus">${e(profile.education.focus)}</p><details><summary>Relevant coursework <span aria-hidden="true">+</span></summary><ul>${profile.education.courses.map(c=>`<li>${e(c)}</li>`).join('')}</ul></details></aside></div><div class="skills-grid" id="skills">${profile.skills.map(s=>`<div><h3>${e(s.group)}</h3><p>${s.items.map(e).join(' · ')}</p></div>`).join('')}</div></section>
<section class="recognition-section" id="recognition"><div class="wrap section">${sectionTop('04','Recognition & learning','Growth, in practice.')}<div class="recognition-grid">${profile.recognition.slice(0,2).map(r=>`<article><span class="small-label">${e(r.org)}</span><h3>${e(r.title)}</h3><p>${e(r.text)}</p></article>`).join('')}</div></div></section>
<section class="wrap section" id="certifications">${sectionTop('05','Certifications','Learning, continued.')}<div class="recognition-grid">${profile.recognition.slice(2).map(r=>`<article><span class="small-label">${e(r.org)}</span><h3>${e(r.title)}</h3><p>${e(r.text)}</p></article>`).join('')}</div></section>
<section class="wrap section community">${sectionTop('05','Beyond engineering','Teams, campus & community.')}<div class="community-grid">${profile.community.map(c=>`<article><h3>${e(c.title)}</h3><span class="small-label">${e(c.org)}</span><p>${e(c.text)}</p></article>`).join('')}</div></section>
<section class="contact"><div class="wrap contact-inner"><div><p class="eyebrow">Get in touch</p><h2>Let’s start a<br>conversation<span class="lime-text">.</span></h2></div><div><p>For software engineering, graduate study,<br>or a conversation about a project.</p><a class="email-link" href="mailto:${profile.email}">${profile.email} ${arrow}</a><div class="contact-links"><a href="${profile.linkedin}">LinkedIn ${arrow}</a><a href="${profile.github}">GitHub ${arrow}</a></div></div></div></section>`;
write('index.html', frame(`${profile.name} — Software Developer`, 'Software developer at Amdocs. Explore enterprise software experience and projects in audio recognition, EEG classification, computer vision, and web applications.', '/', home, true));
projects.forEach((p,i)=>{
 const next=projects[(i+1)%projects.length];
 const body=`<section class="case-hero"><div class="wrap"><a class="back-link" href="/#work">← All projects</a><p class="eyebrow">${e(p.category)}</p><h1>${e(p.name)}</h1><p class="case-summary">${e(p.summary)}</p><div class="case-meta"><span>${e(p.type)}</span><span>${e(p.status)}</span></div>${tags(p.tech)}</div></section><div class="wrap case-diagram">${figure(p)}</div><section class="wrap case-body"><aside class="case-sidebar"><h2>On this page</h2><a href="#overview">Overview</a><a href="#contribution">Contribution</a><a href="#approach">Approach</a><a href="#results">Results & scope</a><a href="#reflection">Reflection</a></aside><div class="case-text"><section id="overview"><p class="eyebrow">The question</p><h2>${e(p.question)}</h2><p>${e(p.context)}</p></section><section id="contribution"><h2>My contribution</h2><p>${e(p.role)}</p></section><section id="approach"><h2>How it works</h2>${p.work.map((w,j)=>`<article class="approach"><div><h3>${e(w.title)}</h3><p>${e(w.text)}</p></div></article>`).join('')}</section><section id="results"><h2>Results & scope</h2>${p.metric?`<div class="result"><strong>${e(p.metric.value)}</strong><span>${e(p.metric.label)}</span></div>`:''}<p>${e(p.outcome)}</p><div class="scope-note"><h3>Evaluation boundary</h3><p>${e(p.limits)}</p></div></section><section id="reflection"><h2>Engineering reflection</h2><p>${e(p.takeaway)}</p></section></div></section><div class="wrap next-project"><span class="eyebrow">Next case study</span><a href="/projects/${next.slug}/">${e(next.name)} ${arrow}</a></div>`;
 write(`projects/${p.slug}/index.html`,frame(`${p.name} — ${profile.name}`,p.summary,`/projects/${p.slug}/`,body));
});
const resume=`<section class="wrap section resume-page"><a class="back-link" href="/">← Back to portfolio</a><div class="resume-heading"><div><p class="eyebrow">Professional résumé</p><h1>${e(profile.name)}</h1><p>${e(profile.role)} · ${e(profile.location)}</p></div><a class="button dark" href="/assets/Jagjeevan_Singh_Soni_Resume.pdf" target="_blank" rel="noopener noreferrer">View Resume ↗</a></div><p class="resume-summary">${e(profile.about)}</p><div class="resume-section"><h2>Experience</h2><h3>Amdocs · ${e(profile.experience.current)}</h3><p class="small-label">${e(profile.experience.period)} · Previously ${e(profile.experience.previous)}</p><ul>${profile.experience.areas.map(a=>`<li>${e(a.text)}</li>`).join('')}</ul></div><div class="resume-section"><h2>Education</h2><h3>${e(profile.education.degree)}</h3><p>${e(profile.education.school)} · ${e(profile.education.period)}<br>${e(profile.education.grade)} · ${e(profile.education.focus)}</p></div><div class="resume-section"><h2>Selected projects</h2>${projects.map(p=>`<article><h3><a href="/projects/${p.slug}/">${e(p.name)} ${arrow}</a></h3><p>${e(p.summary)}</p><p class="small-label">${p.tech.map(e).join(' · ')}<br>${e(p.status)}</p></article>`).join('')}</div><div class="resume-section"><h2>Technical skills</h2>${profile.skills.map(s=>`<p><strong>${e(s.group)}:</strong> ${s.items.map(e).join(', ')}</p>`).join('')}</div><div class="resume-section"><h2>Recognition & leadership</h2>${[...profile.recognition.slice(0,2),...profile.community].map(x=>`<p><strong>${e(x.title)}</strong> · ${e(x.org)}<br>${e(x.text)}</p>`).join('')}</div><p><a href="mailto:${profile.email}">${profile.email}</a> · <a href="${profile.linkedin}">LinkedIn</a> · <a href="${profile.github}">GitHub</a></p></section>`;
write('resume/index.html',frame(`Résumé — ${profile.name}`,'Experience, education, projects, and technical skills. View the professional résumé as a PDF.','/resume/',resume));
write('404.html',frame(`Page not found — ${profile.name}`,'Return to the portfolio homepage.','/404.html',`<section class="wrap section not-found"><p class="eyebrow">404 / Page not found</p><h1>This page has<br>moved off course.</h1><p>You can find my experience and selected projects on the homepage.</p><a class="button dark" href="/">Back to the portfolio →</a></section>`));
write('.nojekyll','');
write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${profile.url}/sitemap.xml\n`);
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/resume/',...projects.map(p=>`/projects/${p.slug}/`)].map(u=>`<url><loc>${profile.url}${u}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${projects.length+3} HTML pages in dist/`);
