import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const profile=JSON.parse(fs.readFileSync('content/profile.json','utf8'));
const projects=JSON.parse(fs.readFileSync('content/projects.json','utf8'));
const root=path.resolve('dist');
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(f=>f.isDirectory()?walk(path.join(dir,f.name)):[path.join(dir,f.name)]);
const files=walk(root); const pages=files.filter(p=>p.endsWith('.html'));
let links=0;
for(const page of pages){
 const html=fs.readFileSync(page,'utf8');
 assert(!/\uFFFD|â€|Â·|Ã/.test(html),`${page}: corrupted character encoding`);
 assert.equal((html.match(/\bdownload="/g)||[]).length,1,`${page}: one resume download per page`);
 assert(/<header[\s\S]*\bdownload="[\s\S]*<\/header>/.test(html),`${page}: download must be in header`);
 assert(html.includes('>JJ<span>.</span>'),`${page}: JJ monogram`);
 for(const theme of ['light','dark'])assert(html.includes(`data-theme-choice="${theme}"`),`${page}: ${theme} theme option`);
 assert.equal((html.match(/<h1[ >]/g)||[]).length,1,`${page}: exactly one h1`);
 for(const check of ['lang="en"','name="viewport"','name="description"','rel="canonical"','id="main"','Skip to content'])assert(html.includes(check),`${page}: ${check}`);
 assert(!/chatgpt|openai|co-authored-by|generated by|built with ai|powered by ai|watermark/i.test(html),`${page}: unwanted attribution`);
 const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
 assert.equal(new Set(ids).size,ids.length,`${page}: duplicate IDs`);
 for(const match of html.matchAll(/\b(?:href|src)="([^"]+)"/g)){
  const href=match[1]; if(/^(https?:|mailto:)/.test(href))continue;
  const [pathname,anchor]=href.split('#');
  let target=pathname?path.join(root,pathname):page;
  if(pathname.endsWith('/'))target=path.join(target,'index.html');
  assert(fs.existsSync(target),`${page}: missing ${href}`);
  if(anchor){const text=fs.readFileSync(target,'utf8');assert(text.includes(`id="${anchor}"`),`${page}: missing anchor ${href}`);}
  links++;
 }
}
assert.equal(pages.length,7);
assert(files.every(p=>!p.endsWith('.docx')&&!p.includes('.local')),'Unexpected private source file in output');
assert(fs.statSync(path.join(root,'assets/Jagjeevan_Singh_Soni_Resume.pdf')).size>1000);
const pdf=fs.readFileSync(path.join(root,profile.resume.file));
assert.equal(crypto.createHash('sha256').update(pdf).digest('hex'),profile.resume.sha256,'Supplied PDF must remain byte-identical');
assert(pdf.subarray(0,5).toString()==='%PDF-','Resume must be a PDF');
const escape=value=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const filename of ['index.html','resume/index.html'])assert(fs.readFileSync(path.join(root,filename),'utf8').includes(escape(profile.summary)),`${filename}: exact resume summary`);
const home=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const id of ['overview','experience','work','education','skills','recognition','community','contact']){
 assert(home.includes(`href="#${id}" data-section-link`),`Missing section navigation: ${id}`);
 assert(home.includes(`id="${id}" data-section`),`Missing navigable section: ${id}`);
}
for(const project of projects){
 assert(home.includes(`href="#project-${project.slug}"`),`Missing direct project navigation: ${project.slug}`);
 for(const key of ['summary','plainRole','plainResult'])assert(home.includes(escape(project[key])),`${project.slug}: missing ${key}`);
}
assert(!fs.existsSync('scripts/resume.py'),'A generator must not overwrite the supplied PDF');
assert(!home.includes('<details class="coursework">'),'Coursework must be directly visible');
assert.equal((home.match(/class="skill-card /g)||[]).length,6,'Six organized skill cards');
console.log(`Passed: ${pages.length} pages, ${links} internal references, section/project navigation, exact summary, PDF identity, metadata, and output isolation.`);
