import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve('dist');
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(f=>f.isDirectory()?walk(path.join(dir,f.name)):[path.join(dir,f.name)]);
const files=walk(root); const pages=files.filter(p=>p.endsWith('.html'));
let links=0;
for(const page of pages){
 const html=fs.readFileSync(page,'utf8');
 assert.equal((html.match(/<h1[ >]/g)||[]).length,1,`${page}: exactly one h1`);
 for(const check of ['lang="en"','name="viewport"','name="description"','rel="canonical"','id="main"','Skip to content'])assert(html.includes(check),`${page}: ${check}`);
 assert(!/chatgpt|openai|co-authored-by|generated by|built with ai|powered by ai|watermark/i.test(html),`${page}: unwanted attribution`);
 const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
 assert.equal(new Set(ids).size,ids.length,`${page}: duplicate IDs`);
 for(const match of html.matchAll(/\b(?:href|src)="([^"]+)"/g)){
  const href=match[1]; if(/^(https?:|mailto:)/.test(href))continue;
  const [pathname,anchor]=href.split('#');
  let target=pathname?path.join(root,pathname):page;
  if(pathname.endsWith('/'))target=path.join(target,'index.html');
  assert(fs.existsSync(target),`${page}: missing ${href}`);
  if(anchor){const text=fs.readFileSync(target,'utf8');assert(text.includes(`id="${anchor}"`),`${page}: missing anchor ${href}`);}
  links++;
 }
}
assert.equal(pages.length,7);
assert(files.every(p=>!p.endsWith('.docx')&&!p.includes('.local')),'Unexpected private source file in output');
assert(fs.statSync(path.join(root,'assets/Jagjeevan_Singh_Soni_Resume.pdf')).size>1000);
console.log(`Passed: ${pages.length} pages, ${links} internal references, metadata, headings, output isolation, and attribution checks.`);
